CREATE DATABASE IF NOT EXISTS amanin;
USE amanin;

CREATE TABLE IF NOT EXISTS scans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR(255) NOT NULL,
  skor INT NOT NULL,
  grade VARCHAR(2) NOT NULL,
  detail JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);